apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight
  namespace: redis
  labels:
    app: redisinsight
spec:
  replicas: 1
  strategy:
    type: Recreate # PVC 사용 시 충돌 방지
  selector:
    matchLabels:
      app: redisinsight
  template:
    metadata:
      labels:
        app: redisinsight
    spec:
      volumes:
        - name: redisinsight-data
          persistentVolumeClaim:
            claimName: redisinsight-pv-claim
      # 공식 문서 권장: 볼륨 권한 문제를 해결하기 위한 초기화 컨테이너
      initContainers:
        - name: init
          image: busybox
          command: ["/bin/sh", "-c", "chown -R 1000 /data"]
          volumeMounts:
            - name: redisinsight-data
              mountPath: /data
      containers:
        - name: redisinsight
          image: redis/redisinsight:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: RI_APP_HOST
              value: "0.0.0.0"
            - name: RI_APP_PORT
              value: "5540"
          ports:
            - containerPort: 5540
              protocol: TCP
          volumeMounts:
            - name: redisinsight-data
              mountPath: /data
