apiVersion: v1
kind: Service
metadata:
  name: redisinsight-service # 공식 가이드에 따라 충돌 방지를 위해 -service를 붙임
  namespace: redis
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5540
  selector:
    app: redisinsight
